### PR TITLE
Restructure repo to match phase convention

### PR DESCRIPTION
**Pull request by jdiaz4302**
Some work has already begun on this project, but this PR is taking a step back to reorganize the repository to match the branch's phase convention; this will allow people to more easily understand and contribute to the project.

### CODE REVIEW

**Comment by jdiaz4302** [comment]
Updating with the new commits:

The individual tasks within the original script are now broken into smaller scripts/functions. Each function has the associated libraries attached. The code still has ad-hoc properties such as containing many specific inputs (e.g., file names, plotting parameters), but I did move some of these file names to default function arguments so they could be easily and directly changed. The plotting parameters are much more fine tuned, so I left them alone. 

The way you would run this new set up is as follows:

* Navigate to `1_fetch/src/fetch_model_RMSEs.R`, run the script to load the proper libraries and define the function, then run `fetch_data()` to download the data
* Navigate to `2_process/src/process_model_RMSEs.R`, run the script to load the proper libraries and define the function, then run `eval_data <- import_cleaned_data()` to import and store the data, assign the visualization properties, and save the result
* Navigate to `3_visualize/src/create_RMSE_figure1.R`, run the script to define the function, then run `plot_RMSEs()` to create the figure
* Navigate to `3_visualize/src/create_RMSE_table1.R`, run the script to load the proper libraries and define the function, then run `tabularize_RMSEs(eval_data)` to retrieve the key metrics and populate the text with those numbers

**Review by lindsayplatt — COMMENTED** [review]
My only suggestion is related to filenames. 

1. Instead of setting a default file names and dirs, I would suggest passing those in to the function as a requirement to using the function. This will set you up better for when you switch to targets.
2. Update so that the output files end up in the phase directory structures. So instead of `'mydir'`, they should be going into `1_fetch/out`, `3_visualize/out/`, etc.

**Comment by jdiaz4302** [comment]
Hi @lindsayplatt,

I have now removed the default arguments and this would be the new usage that would allow proper storage that mimics the original script:

* Navigate to `1_fetch/src/fetch_model_RMSEs.R`, run the script to load the proper libraries and define the function, then run `fetch_data('1_fetch/out/', 'model_RMSEs.csv', '5d925066e4b0c4f70d0d0599', 'me_RMSE.csv')`
* Navigate to `2_process/src/process_model_RMSEs.R`, run the script to load the proper libraries and define the function, then run `eval_data <- import_cleaned_data('1_fetch/out/', 'model_RMSEs.csv', '2_process/out/', 'model_summary_results.csv')` to import and store the data, assign the visualization properties, and save the result
* Navigate to `3_visualize/src/create_RMSE_figure1.R`, run the script to define the function, then run `plot_RMSEs('3_visualize/out/', 'figure_1.png')` to create the figure
* Navigate to `3_visualize/src/create_RMSE_table1.R`, run the script to load the proper libraries and define the function, then run `tabularize_RMSEs(eval_data, '3_visualize/out/', 'model_diagnostic_text.txt')` to retrieve the key metrics and populate the text with those numbers

**Comment by jdiaz4302** [comment]
I have updated the function's argument names to make this more generalizable/intuitive. The general use would be:
* `fetch_data(output_directory, output_file, ScienceBase_id, ScienceBase_file)`
* `eval_data <- import_cleaned_data(input_directory, input_file, output_directory, output_file)`
    * where the input here is the output of the latter
* `plot_RMSEs(output_directory, output_file)`
* `tabularize_RMSEs(eval_data, output_directory, output_file)`

**Review by lindsayplatt — APPROVED** [review]
great changes 🎉

**Pull request merged**
